import { describe, expect, it } from 'vitest';
import { generateImage } from '../../src/mastra/agents/chat';
import { getImage } from '../../src/mastra/lib/image-store';
import { callTool } from '../helpers/call-tool';

/**
 * generateImage calls OpenAI's /images/generations directly (not through the model
 * router). Under the test env OPENAI_BASE_URL points at AIMock, whose image fixture
 * answers, so this runs the real tool with zero spend.
 */
describe('generateImage', () => {
  it('stores the generated bytes and hands back only an id', async () => {
    const out = await callTool<{ imageId: string; mediaType: string; prompt: string }>(
      generateImage,
      { prompt: 'a teal square' },
    );

    expect(out.mediaType).toBe('image/webp');
    expect(out.prompt).toBe('a teal square');
    // The model gets the id; the bytes stay server-side for GET /images/:id.
    // These are the image fixture's exact bytes, so the request really went out.
    expect(getImage(out.imageId)?.base64).toBe('UklGRiQAAABXRUJQ');
  });
});
